### ISSUE TITLE
upgrade from version 3.42.20 to 3.42.22 

### ISSUE THREAD

**Issue by anthonymidili** [heroku/heroku#1852]
Ever since upgrading to version 3.42.22 from 3.42.20 I have been getting this error. I'm on a older imac that is 32bit and https://cli-assets.heroku.com/master/manifest.json doesn't have an entry for 386 darwin.

> Heroku client internal error.
undefined method `[]' for nil:NilClass
/usr/local/Cellar/heroku-toolbelt/3.42.22/libexec/lib/heroku/jsplugin.rb:211:in `url'
/usr/local/Cellar/heroku-toolbelt/3.42.22/libexec/lib/heroku/jsplugin.rb:135:in `setup'
/usr/local/Cellar/heroku-toolbelt/3.42.22/libexec/lib/heroku/cli.rb:24:in `start'
/usr/local/Cellar/heroku-toolbelt/3.42.22/libexec/bin/heroku:24:in `<main>'
Heroku client internal error.
undefined method `[]' for nil:NilClass
/usr/local/Cellar/heroku-toolbelt/3.42.22/libexec/lib/heroku/jsplugin.rb:211:in `url'
/usr/local/Cellar/heroku-toolbelt/3.42.22/libexec/lib/heroku/jsplugin.rb:135:in `setup'
/usr/local/Cellar/heroku-toolbelt/3.42.22/libexec/lib/heroku/cli.rb:24:in `start'
/usr/local/Cellar/heroku-toolbelt/3.42.22/libexec/bin/heroku:24:in `<main>'
Heroku client internal error.
undefined method `[]' for nil:NilClass
/usr/local/Cellar/heroku-toolbelt/3.42.22/libexec/lib/heroku/jsplugin.rb:211:in `url'
/usr/local/Cellar/heroku-toolbelt/3.42.22/libexec/lib/heroku/jsplugin.rb:135:in `setup'
/usr/local/Cellar/heroku-toolbelt/3.42.22/libexec/lib/heroku/cli.rb:24:in `start'
/usr/local/Cellar/heroku-toolbelt/3.42.22/libexec/bin/heroku:24:in `<main>'
Heroku client internal error.
undefined method `[]' for nil:NilClass
/usr/local/Cellar/heroku-toolbelt/3.42.22/libexec/lib/heroku/jsplugin.rb:211:in `url'
/usr/local/Cellar/heroku-toolbelt/3.42.22/libexec/lib/heroku/jsplugin.rb:135:in `setup'
/usr/local/Cellar/heroku-toolbelt/3.42.22/libexec/lib/heroku/cli.rb:24:in `start'
/usr/local/Cellar/heroku-toolbelt/3.42.22/libexec/bin/heroku:24:in `<main>'
> /.heroku/error.log

**Comment by dickeyxxx** [comment]
we do not support non 64 bit versions of osx anymore
