### PR TITLE
Merge DATABASE_URL with another alias in pg:info

### PR DESCRIPTION
**Pull request by bjeanes**
Merge `DATABASE_URL` with another alias in `pg:info` if there is another name. Otherwise, continue to present it as a first normal attachment.

---

Addresses #1605 in the short term, but does not implement the new output discussed in that issue.

This fixes a regression introduced by #1564, which was designed to show `DATABASE_URL` in the output if the database had no other alias. Instead, it always showed `DATABASE_URL`, even when it was a supplementary name for a colour-based one. While that is more correct, it is also less familiar to customers and should be addressed directly, as discussed towards the end of #1605.

cc @chadbailey59 @neovintage @diwu1989 @stevo550 @heroku/add-ons

### CODE REVIEW

**Comment by bjeanes** [comment]
The behaviour is now:

```sh-session
$ bin/heroku pg:info -a bjeanes
=== HEROKU_POSTGRESQL_CRIMSON_URL (DATABASE_URL)
Plan:        Dev
Status:      Available
Connections: 2/20
PG Version:  9.1.15
Created:     2012-09-27 23:52 UTC
Data Size:   11.5 MB
Tables:      3
Rows:        98/10000 (In compliance)
Fork/Follow: Unsupported
Rollback:    Unsupported

=== HEROKU_POSTGRESQL_OLIVE_URL
Plan:        Hobby-dev
Status:      Available
Connections: 0/20
PG Version:  9.3.6
Created:     2015-04-21 03:15 UTC
Data Size:   6.2 MB
Tables:      0
Rows:        0/10000 (In compliance)
Fork/Follow: Unsupported
Rollback:    Unsupported

$ heroku addons:detach CRIMSON -a bjeanes
Removing HEROKU_POSTGRESQL_CRIMSON attachment to budding-busily-2230 from bjeanes... done
Unsetting HEROKU_POSTGRESQL_CRIMSON vars and restarting bjeanes... done, v154

$ heroku pg:info -a bjeanes
=== DATABASE_URL
Plan:        Dev
Status:      Available
Connections: 2/20
PG Version:  9.1.15
Created:     2012-09-27 23:52 UTC
Data Size:   11.5 MB
Tables:      3
Rows:        98/10000 (In compliance)
Fork/Follow: Unsupported
Rollback:    Unsupported

=== HEROKU_POSTGRESQL_OLIVE_URL
Plan:        Hobby-dev
Status:      Available
Connections: 0/20
PG Version:  9.3.6
Created:     2015-04-21 03:15 UTC
Data Size:   6.2 MB
Tables:      0
Rows:        0/10000 (In compliance)
Fork/Follow: Unsupported
Rollback:    Unsupported
```

However, note that if there is more than 2 attachments to the same DB, *other than* `DATABASE_URL`, the behaviour is less defined and is better addressed as discussed in #1605. That is, one of the colour URLs will arbitrarily be "elected" as the primary and the second colour will simply be another entry. Here, `DATABASE`, `CRIMSON`, and `JADE` are all aliases for the same database instance:

``` sh-session
$ heroku pg:info -a bjeanes
=== HEROKU_POSTGRESQL_CRIMSON_URL
Plan:        Dev
Status:      Available
Connections: 1/20
PG Version:  9.1.15
Created:     2012-09-27 23:52 UTC
Data Size:   11.5 MB
Tables:      3
Rows:        98/10000 (In compliance)
Fork/Follow: Unsupported
Rollback:    Unsupported

=== HEROKU_POSTGRESQL_JADE_URL (DATABASE_URL)
Plan:        Dev
Status:      Available
Connections: 1/20
PG Version:  9.1.15
Created:     2012-09-27 23:52 UTC
Data Size:   11.5 MB
Tables:      3
Rows:        98/10000 (In compliance)
Fork/Follow: Unsupported
Rollback:    Unsupported

=== HEROKU_POSTGRESQL_OLIVE_URL
Plan:        Hobby-dev
Status:      Available
Connections: 0/20
PG Version:  9.3.6
Created:     2015-04-21 03:15 UTC
Data Size:   6.2 MB
Tables:      0
Rows:        0/10000 (In compliance)
Fork/Follow: Unsupported
Rollback:    Unsupported
```

**Comment by bjeanes** [comment]
(could probably merge in @chadbailey59's test into this actually, though I haven't checked if it makes it pass since it might be expecting a different solution to this)

**Comment by bjeanes** [comment]
Closing in favour of #1644 I think. We can re-open here if relevant parties aren't keen on the other pull just yet.
